/************************************************************************
ivx_voices.h - The Infovox 230 v1.12 built-in mode table (60 voices):
   twelve languages times five speakers (Male, Female, Child, Giant,
   Zombie). Every field is a value the engine itself reads out of its
   configuration, spelled exactly as its own installer wrote it.

   Copied from infovox/src/ivx_voices.inc (generated by that project's
   tools/gen_voice_table.py from the v1.12 installer's own SETUP.INS),
   with the field names kept but the type stripped of the "ivx::"
   namespace so it compiles under Visual C++ 6 with no other change.
************************************************************************/

#ifndef _IVX_VOICES_
#define _IVX_VOICES_

typedef struct {
   const char *pszModeKey;       // the engine's key name under ...\Modes
   const char *pszDisplayName;   // full product name, e.g. for -list
   const char *pszLanguageName;  // the prefix the engine requires of ModeKey
   const char *pszModeGuid;      // "{...}", the id Select() takes
   const char *pszLanguageId;    // as the engine wants it, decimal
   unsigned short wLcid;         // not read by the engine; kept for reference
   const char *pszLanguageFile;
   const char *pszLibraryFile;
   const char *pszPhSymFile;
   const char *pszSpeakerName;
   const char *pszSpeakerStyle;
   const char *pszGender;        // "1" female, "2" male
   const char *pszAge;
   const char *pszPitch;
   const char *pszDynamic;
   const char *pszAspiration;
   const char *pszFormantNo;
   } IVXVOICE;

static const IVXVOICE g_IvxVoices[] = {
    { "American English Child", "Infovox 1.12 American English Child", "American English", "{c9c5eda0-7c89-11d0-0300-030000000000}", "1033", 0x0409, "amrules.ivx", "", "", "American English Child", "", "2", "6", "90", "57", "15", "3" },
    { "American English Female", "Infovox 1.12 American English Female", "American English", "{c9c5eda0-7c89-11d0-0300-010000000000}", "1033", 0x0409, "amrules.ivx", "", "", "American English Female", "", "1", "30", "73", "53", "0", "1" },
    { "American English Giant", "Infovox 1.12 American English Giant", "American English", "{c9c5eda0-7c89-11d0-0300-020000000000}", "1033", 0x0409, "amrules.ivx", "", "", "American English Giant", "", "2", "30", "50", "25", "0", "2" },
    { "American English Male", "Infovox 1.12 American English Male", "American English", "{c9c5eda0-7c89-11d0-0300-000000000000}", "1033", 0x0409, "amrules.ivx", "", "", "American English Male", "", "2", "30", "50", "32", "0", "0" },
    { "American English Zombie", "Infovox 1.12 American English Zombie", "American English", "{c9c5eda0-7c89-11d0-0300-040000000000}", "1033", 0x0409, "amrules.ivx", "", "", "American English Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "British English Child", "Infovox 1.12 British English Child", "British English", "{c9c5eda0-7c89-11d0-0301-030000000000}", "2057", 0x0809, "blrules.ivx", "", "", "British English Child", "", "2", "6", "90", "57", "15", "3" },
    { "British English Female", "Infovox 1.12 British English Female", "British English", "{c9c5eda0-7c89-11d0-0301-010000000000}", "2057", 0x0809, "blrules.ivx", "", "", "British English Female", "", "1", "30", "73", "53", "0", "1" },
    { "British English Giant", "Infovox 1.12 British English Giant", "British English", "{c9c5eda0-7c89-11d0-0301-020000000000}", "2057", 0x0809, "blrules.ivx", "", "", "British English Giant", "", "2", "30", "50", "25", "0", "2" },
    { "British English Male", "Infovox 1.12 British English Male", "British English", "{c9c5eda0-7c89-11d0-0301-000000000000}", "2057", 0x0809, "blrules.ivx", "", "", "British English Male", "", "2", "30", "50", "32", "0", "0" },
    { "British English Zombie", "Infovox 1.12 British English Zombie", "British English", "{c9c5eda0-7c89-11d0-0301-040000000000}", "2057", 0x0809, "blrules.ivx", "", "", "British English Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Castilian Spanish Child", "Infovox 1.12 Castilian Spanish Child", "Castilian Spanish", "{c9c5eda0-7c89-11d0-030c-030000000000}", "10", 0x040A, "sprules.ivx", "", "", "Castilian Spanish Child", "", "2", "6", "90", "57", "15", "3" },
    { "Castilian Spanish Female", "Infovox 1.12 Castilian Spanish Female", "Castilian Spanish", "{c9c5eda0-7c89-11d0-030c-010000000000}", "10", 0x040A, "sprules.ivx", "", "", "Castilian Spanish Female", "", "1", "30", "73", "53", "0", "1" },
    { "Castilian Spanish Giant", "Infovox 1.12 Castilian Spanish Giant", "Castilian Spanish", "{c9c5eda0-7c89-11d0-030c-020000000000}", "10", 0x040A, "sprules.ivx", "", "", "Castilian Spanish Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Castilian Spanish Male", "Infovox 1.12 Castilian Spanish Male", "Castilian Spanish", "{c9c5eda0-7c89-11d0-030c-000000000000}", "10", 0x040A, "sprules.ivx", "", "", "Castilian Spanish Male", "", "2", "30", "50", "30", "0", "0" },
    { "Castilian Spanish Zombie", "Infovox 1.12 Castilian Spanish Zombie", "Castilian Spanish", "{c9c5eda0-7c89-11d0-030c-040000000000}", "10", 0x040A, "sprules.ivx", "", "", "Castilian Spanish Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Danish Child", "Infovox 1.12 Danish Child", "Danish", "{c9c5eda0-7c89-11d0-0302-030000000000}", "6", 0x0406, "darules.ivx", "darules.dll", "", "Danish Child", "", "2", "6", "90", "57", "15", "3" },
    { "Danish Female", "Infovox 1.12 Danish Female", "Danish", "{c9c5eda0-7c89-11d0-0302-010000000000}", "6", 0x0406, "darules.ivx", "darules.dll", "", "Danish Female", "", "1", "30", "73", "51", "0", "1" },
    { "Danish Giant", "Infovox 1.12 Danish Giant", "Danish", "{c9c5eda0-7c89-11d0-0302-020000000000}", "6", 0x0406, "darules.ivx", "darules.dll", "", "Danish Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Danish Male", "Infovox 1.12 Danish Male", "Danish", "{c9c5eda0-7c89-11d0-0302-000000000000}", "6", 0x0406, "darules.ivx", "darules.dll", "", "Danish Male", "", "2", "30", "50", "32", "0", "0" },
    { "Danish Zombie", "Infovox 1.12 Danish Zombie", "Danish", "{c9c5eda0-7c89-11d0-0302-040000000000}", "6", 0x0406, "darules.ivx", "darules.dll", "", "Danish Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Dutch Child", "Infovox 1.12 Dutch Child", "Dutch", "{c9c5eda0-7c89-11d0-0304-030000000000}", "19", 0x0413, "durules.ivx", "", "", "Dutch Child", "", "2", "6", "90", "57", "15", "3" },
    { "Dutch Female", "Infovox 1.12 Dutch Female", "Dutch", "{c9c5eda0-7c89-11d0-0304-010000000000}", "19", 0x0413, "durules.ivx", "", "", "Dutch Female", "", "1", "30", "75", "53", "0", "1" },
    { "Dutch Giant", "Infovox 1.12 Dutch Giant", "Dutch", "{c9c5eda0-7c89-11d0-0304-020000000000}", "19", 0x0413, "durules.ivx", "", "", "Dutch Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Dutch Male", "Infovox 1.12 Dutch Male", "Dutch", "{c9c5eda0-7c89-11d0-0304-000000000000}", "19", 0x0413, "durules.ivx", "", "", "Dutch Male", "", "2", "30", "50", "32", "0", "0" },
    { "Dutch Zombie", "Infovox 1.12 Dutch Zombie", "Dutch", "{c9c5eda0-7c89-11d0-0304-040000000000}", "19", 0x0413, "durules.ivx", "", "", "Dutch Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Finnish Child", "Infovox 1.12 Finnish Child", "Finnish", "{c9c5eda0-7c89-11d0-0305-030000000000}", "11", 0x040B, "firules.ivx", "", "", "Finnish Child", "", "2", "6", "90", "57", "15", "3" },
    { "Finnish Female", "Infovox 1.12 Finnish Female", "Finnish", "{c9c5eda0-7c89-11d0-0305-010000000000}", "11", 0x040B, "firules.ivx", "", "", "Finnish Female", "", "1", "30", "75", "36", "0", "1" },
    { "Finnish Giant", "Infovox 1.12 Finnish Giant", "Finnish", "{c9c5eda0-7c89-11d0-0305-020000000000}", "11", 0x040B, "firules.ivx", "", "", "Finnish Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Finnish Male", "Infovox 1.12 Finnish Male", "Finnish", "{c9c5eda0-7c89-11d0-0305-000000000000}", "11", 0x040B, "firules.ivx", "", "", "Finnish Male", "", "2", "30", "50", "25", "0", "0" },
    { "Finnish Zombie", "Infovox 1.12 Finnish Zombie", "Finnish", "{c9c5eda0-7c89-11d0-0305-040000000000}", "11", 0x040B, "firules.ivx", "", "", "Finnish Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "French Child", "Infovox 1.12 French Child", "French", "{c9c5eda0-7c89-11d0-0306-030000000000}", "12", 0x040C, "frrules.ivx", "", "", "French Child", "", "2", "6", "90", "57", "15", "3" },
    { "French Female", "Infovox 1.12 French Female", "French", "{c9c5eda0-7c89-11d0-0306-010000000000}", "12", 0x040C, "frrules.ivx", "", "", "French Female", "", "1", "30", "73", "53", "0", "1" },
    { "French Giant", "Infovox 1.12 French Giant", "French", "{c9c5eda0-7c89-11d0-0306-020000000000}", "12", 0x040C, "frrules.ivx", "", "", "French Giant", "", "2", "30", "50", "25", "0", "2" },
    { "French Male", "Infovox 1.12 French Male", "French", "{c9c5eda0-7c89-11d0-0306-000000000000}", "12", 0x040C, "frrules.ivx", "", "", "French Male", "", "2", "30", "50", "32", "0", "0" },
    { "French Zombie", "Infovox 1.12 French Zombie", "French", "{c9c5eda0-7c89-11d0-0306-040000000000}", "12", 0x040C, "frrules.ivx", "", "", "French Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "German Child", "Infovox 1.12 German Child", "German", "{c9c5eda0-7c89-11d0-0307-030000000000}", "7", 0x0407, "gerules.ivx", "", "", "German Child", "", "2", "6", "90", "57", "15", "3" },
    { "German Female", "Infovox 1.12 German Female", "German", "{c9c5eda0-7c89-11d0-0307-010000000000}", "7", 0x0407, "gerules.ivx", "", "", "German Female", "", "1", "30", "73", "53", "0", "1" },
    { "German Giant", "Infovox 1.12 German Giant", "German", "{c9c5eda0-7c89-11d0-0307-020000000000}", "7", 0x0407, "gerules.ivx", "", "", "German Giant", "", "2", "30", "50", "25", "0", "2" },
    { "German Male", "Infovox 1.12 German Male", "German", "{c9c5eda0-7c89-11d0-0307-000000000000}", "7", 0x0407, "gerules.ivx", "", "", "German Male", "", "2", "30", "50", "25", "0", "0" },
    { "German Zombie", "Infovox 1.12 German Zombie", "German", "{c9c5eda0-7c89-11d0-0307-040000000000}", "7", 0x0407, "gerules.ivx", "", "", "German Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Icelandic Child", "Infovox 1.12 Icelandic Child", "Icelandic", "{c9c5eda0-7c89-11d0-0308-030000000000}", "15", 0x040F, "icrules.ivx", "", "", "Icelandic Child", "", "2", "6", "90", "57", "15", "3" },
    { "Icelandic Female", "Infovox 1.12 Icelandic Female", "Icelandic", "{c9c5eda0-7c89-11d0-0308-010000000000}", "15", 0x040F, "icrules.ivx", "", "", "Icelandic Female", "", "1", "30", "68", "53", "0", "1" },
    { "Icelandic Giant", "Infovox 1.12 Icelandic Giant", "Icelandic", "{c9c5eda0-7c89-11d0-0308-020000000000}", "15", 0x040F, "icrules.ivx", "", "", "Icelandic Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Icelandic Male", "Infovox 1.12 Icelandic Male", "Icelandic", "{c9c5eda0-7c89-11d0-0308-000000000000}", "15", 0x040F, "icrules.ivx", "", "", "Icelandic Male", "", "2", "30", "50", "32", "0", "0" },
    { "Icelandic Zombie", "Infovox 1.12 Icelandic Zombie", "Icelandic", "{c9c5eda0-7c89-11d0-0308-040000000000}", "15", 0x040F, "icrules.ivx", "", "", "Icelandic Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Italian Child", "Infovox 1.12 Italian Child", "Italian", "{c9c5eda0-7c89-11d0-0309-030000000000}", "16", 0x0410, "itrules.ivx", "", "", "Italian Child", "", "2", "6", "90", "57", "15", "3" },
    { "Italian Female", "Infovox 1.12 Italian Female", "Italian", "{c9c5eda0-7c89-11d0-0309-010000000000}", "16", 0x0410, "itrules.ivx", "", "", "Italian Female", "", "1", "30", "73", "53", "0", "1" },
    { "Italian Giant", "Infovox 1.12 Italian Giant", "Italian", "{c9c5eda0-7c89-11d0-0309-020000000000}", "16", 0x0410, "itrules.ivx", "", "", "Italian Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Italian Male", "Infovox 1.12 Italian Male", "Italian", "{c9c5eda0-7c89-11d0-0309-000000000000}", "16", 0x0410, "itrules.ivx", "", "", "Italian Male", "", "2", "30", "50", "30", "0", "0" },
    { "Italian Zombie", "Infovox 1.12 Italian Zombie", "Italian", "{c9c5eda0-7c89-11d0-0309-040000000000}", "16", 0x0410, "itrules.ivx", "", "", "Italian Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Norwegian Child", "Infovox 1.12 Norwegian Child", "Norwegian", "{c9c5eda0-7c89-11d0-030a-030000000000}", "20", 0x0414, "norules.ivx", "", "", "Norwegian Child", "", "2", "6", "90", "57", "15", "3" },
    { "Norwegian Female", "Infovox 1.12 Norwegian Female", "Norwegian", "{c9c5eda0-7c89-11d0-030a-010000000000}", "20", 0x0414, "norules.ivx", "", "", "Norwegian Female", "", "1", "30", "73", "53", "0", "1" },
    { "Norwegian Giant", "Infovox 1.12 Norwegian Giant", "Norwegian", "{c9c5eda0-7c89-11d0-030a-020000000000}", "20", 0x0414, "norules.ivx", "", "", "Norwegian Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Norwegian Male", "Infovox 1.12 Norwegian Male", "Norwegian", "{c9c5eda0-7c89-11d0-030a-000000000000}", "20", 0x0414, "norules.ivx", "", "", "Norwegian Male", "", "2", "30", "50", "32", "0", "0" },
    { "Norwegian Zombie", "Infovox 1.12 Norwegian Zombie", "Norwegian", "{c9c5eda0-7c89-11d0-030a-040000000000}", "20", 0x0414, "norules.ivx", "", "", "Norwegian Zombie", "", "2", "30", "50", "38", "0", "4" },
    { "Swedish Child", "Infovox 1.12 Swedish Child", "Swedish", "{c9c5eda0-7c89-11d0-030e-030000000000}", "29", 0x041D, "swrules.ivx", "", "swphsym", "Swedish Child", "", "2", "6", "90", "57", "15", "3" },
    { "Swedish Female", "Infovox 1.12 Swedish Female", "Swedish", "{c9c5eda0-7c89-11d0-030e-010000000000}", "29", 0x041D, "swrules.ivx", "", "swphsym", "Swedish Female", "", "1", "30", "73", "47", "0", "1" },
    { "Swedish Giant", "Infovox 1.12 Swedish Giant", "Swedish", "{c9c5eda0-7c89-11d0-030e-020000000000}", "29", 0x041D, "swrules.ivx", "", "swphsym", "Swedish Giant", "", "2", "30", "50", "25", "0", "2" },
    { "Swedish Male", "Infovox 1.12 Swedish Male", "Swedish", "{c9c5eda0-7c89-11d0-030e-000000000000}", "29", 0x041D, "swrules.ivx", "", "swphsym", "Swedish Male", "", "2", "30", "50", "32", "0", "0" },
    { "Swedish Zombie", "Infovox 1.12 Swedish Zombie", "Swedish", "{c9c5eda0-7c89-11d0-030e-040000000000}", "29", 0x041D, "swrules.ivx", "", "swphsym", "Swedish Zombie", "", "2", "30", "50", "38", "0", "4" },
   };

#define NUM_IVX_VOICES (sizeof(g_IvxVoices) / sizeof(g_IvxVoices[0]))

#endif /* _IVX_VOICES_ */
